version: '3.3'

services:
  redis:
    image: 'redis:alpine'
    networks:
      - app-network

  web:
    build:
      context: .
    image: myapp_web:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - app-network

  celery:
    build:
      context: .
    image: myapp_celery:latest
    command: celery -A djangospider worker --pool=solo -E
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    networks:
      - app-network

networks:
  app-network:
