# Generated by Django 4.1.4 on 2023-11-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
                ('biggest_upvote', models.IntegerField()),
                ('biggest_upvote_url', models.URLField()),
            ],
        ),
    ]
