# Generated by Django 4.1.4 on 2023-11-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangospider', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='UserStats',
        ),
    ]
