# Generated by Django 4.1.4 on 2023-11-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangospider', '0002_userstats_biggest_downvote_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='biggest_downvote_quote',
            field=models.TextField(default='', max_length=4000),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='biggest_upvote_quote',
            field=models.TextField(default='', max_length=4000),
        ),
    ]
