# Generated by Django 4.1.4 on 2023-11-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangospider', '0002_rename_stats_userstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
