# Generated by Django 4.1.4 on 2024-04-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangospider', '0003_alter_userstats_biggest_downvote_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='dead_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='downvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstats',
            name='y0y_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='biggest_downvote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='biggest_downvote_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='biggest_upvote_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
