# Generated by Django 4.1.4 on 2024-05-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangospider', '0004_userstats_dead_count_userstats_downvote_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='reply_user',
            field=models.JSONField(default=dict),
        ),
    ]
