# Generated by Django 4.1.4 on 2023-11-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangospider', '0005_scrapytask_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapytask',
            name='pid',
            field=models.IntegerField(default=0),
        ),
    ]
