# Generated by Django 4.1.4 on 2023-11-20 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangospider', '0006_scrapytask_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapytask',
            name='pid',
        ),
    ]
