# Generated by Django 4.1.4 on 2023-11-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangospider', '0007_remove_scrapytask_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapytask',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='scrapytask',
            name='task_id',
            field=models.IntegerField(default=0),
        ),
    ]
