# Generated by Django 4.1.4 on 2023-11-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangospider', '0008_scrapytask_username_alter_scrapytask_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapytask',
            name='task_id',
            field=models.CharField(max_length=100),
        ),
    ]
